### ISSUE TITLE
AdminHelpTab buggy

### ISSUE THREAD

**Issue by gerritvanaaken** [outflux3/AdminHelp#5]
The AdminHelpTab does not show up after clean install. The module seems to be buggy – it has no effect on the tab navi of my regular PW pages, and the module configuration does not show up in the list, I had to "guess" the URL:

/processwire/module/edit?name=AdminHelpTab

**Comment by outflux3** [comment]
Hi Gerrit - 

ok hold on, let me take a look - can you let me know what version of PW you are on? Also are you enabling it for any templates, and did you add the template_select field manually or did the module install that field (assuming that you already had FieldtypeTemplates installed?

**Comment by gerritvanaaken** [comment]
- PW 3.0.62
- I tried it without any selected templates, and with some of my most used templates (no effect at all)
- I did the auto-install routine
- What is "FieldtypeTemplates" ?

**Comment by outflux3** [comment]
Sorry, i know this is somewhat problematic and i'm trying to make it easier, but the module instructions do explain it; 

typically if you have FieldtypeTemplates (http://modules.processwire.com/modules/fieldtype-templates/) already installed before you run the auto-install, it will add the templates_select field to the help doc. 

This is required in order for the module to know which help doc(s) to show in the editor for any given template.

You can go and install that module now, and then create a template_select field of FieldtypeTemplate, and add that to your help doc. Then select which template to show the help doc on, using that field.  Then it will look like this on the doc editor:

![edit_page__basic_page_help_ _localhost](https://user-images.githubusercontent.com/1743040/32902427-5ce55706-cac0-11e7-99c6-1c4a01067c9f.jpg)

**Comment by outflux3** [comment]
Also, you shouldn't be able to install AdminHelpTab without FieldtypeTemplates, as it is a requirement, that's probably why you couldn't see it in the modules as a clickable module? 
![modules_ _processwire_ _localhost](https://user-images.githubusercontent.com/1743040/32914476-b0373abe-cae3-11e7-8e01-96a4b65824e8.jpg)

**Comment by gerritvanaaken** [comment]
Thanks for your support! After installing "FieldtypeTemplates" and manually adding the "template_select" field it worked well! No idea why the Tabs-Modul shortly seemed to be installable.
